### ISSUE TITLE
Feature request : Unfolding transformations ?

### ISSUE THREAD

**Issue by ytrezq** [ray33ee/Project-Mylang#1]
I just saw this paper https://www.researchgate.net/publication/357770568_FPGA-based_Implementation_of_SHA-256_with_Improvement_of_Throughput_using_Unfolding_Transformation

**Comment by ray33ee** [comment]
I'm afraid I'm not sure what the issue is or what relevance that paper has to this repo.

Posting issues with no actual issues, context or explanation is not helpful and some clarity would be greatly appreciated

**Comment by ytrezq** [comment]
Sorry, it’s an optimization request in order to make the code mining faster. Please see also https://en.wikipedia.org/wiki/Unfolding_(DSP_implementation)

**Comment by ray33ee** [comment]
What code mining? Could you please explain exactly how it would be relevant to this repo? Perhaps provide an example or a demonstration of how it would be used in this repo?

**Comment by ray33ee** [comment]
OP has not provided an adequate explanation of what the issue is or how this issue can improve the repo, so this issue is closed. 

If OP wishes to provide further explanation I encourage them to open another issue
